### PR TITLE
Sasview 5.0.6 - pre release testing

### PR DESCRIPTION
**Pull request by wpotrzebowski**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender

**Comment by pbeaucage** [comment]
It rerendered in 760abfd, I believe.  Should be good now.  Worth noting that the tarball link is pointing to the rc1 tag so the version (and presumably the sha hash) will need to be updated on release of 5.0.6.

**Comment by wpotrzebowski** [comment]
Thanks @pbeaucage. Yes, we will need to update to 5.0.6 once we are ready to release. We will also need to change bumps version as a new release is on its way (and 5.0.6 should be released with it).

**Comment by wpotrzebowski** [comment]
How can I test if this build works? For 5.0.5 release candidates I was able to do install test version by: `conda create -n sasview -c conda-forge python=3.9 sasview=5.0.4.post36` But I guess in order to be able to do this PR needs to be merged?

**Comment by mrakitin** [comment]
> @mrakitin has it already been rerendered or should I also do something else?

@wpotrzebowski, it does not hurt to render it again to get the latest config files, etc.

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Review by mrakitin — APPROVED** [review]

**Pull request merged**
